"""
Intent Debt Detector — the brain of intent debt detection.

Two jobs:
  1. Decide if a commit/PR was likely AI-generated (confidence score 0-1).
  2. Scan file contents for decisions that need intent captured.

Returns a list of flag dicts ready to be saved as IntentFlag rows.
"""

import re
import logging

logger = logging.getLogger(__name__)

# ── AI-detection keywords ──────────────────────────────────────────────────
AI_KEYWORDS = [
    'copilot', 'ai generated', 'ai-generated', 'accepted suggestion',
    'github copilot', 'cursor', 'codeium', 'chatgpt', 'gpt-4', 'gpt-3',
    'claude', 'gemini', 'tabnine', 'codegen', 'ai suggestion',
    'generated by ai', 'auto-generated', 'llm generated',
]

# ── Patterns for detecting suspicious decisions ────────────────────────────
# Timeout / limit patterns
TIMEOUT_PATTERN = re.compile(
    r'(?:timeout|limit|max|min|retry|retries|delay|interval|ttl|expires?|duration|cooldown)'
    r'\s*[=:]\s*(\d+)',
    re.IGNORECASE,
)

# Magic number in conditionals
CONDITIONAL_THRESHOLD_PATTERN = re.compile(
    r'(?:if|while|elif|else\s+if|when|case)\s*\(.*?'
    r'(?:[<>=!]+\s*(\d+(?:\.\d+)?)|(\d+(?:\.\d+)?)\s*[<>=!]+)',
    re.IGNORECASE,
)

# Hard-coded numbers in assignments (not 0 or 1)
MAGIC_NUMBER_PATTERN = re.compile(
    r'(?:const|let|var|final|val|=)\s*\w*\s*[=:]\s*.*?(\d{2,}(?:\.\d+)?)',
    re.IGNORECASE,
)

# Algorithm choice patterns
ALGORITHM_PATTERNS = re.compile(
    r'\b(?:sort|hash|encrypt|bcrypt|argon2|sha256|sha512|md5|aes|rsa'
    r'|pbkdf2|scrypt|hmac|base64|jwt)\b',
    re.IGNORECASE,
)

# String assumptions (currency codes, status strings, role names)
STRING_ASSUMPTION_PATTERN = re.compile(
    r'["\'](?:INR|USD|EUR|GBP|AED|JPY|CNY|admin|user|moderator'
    r'|pending|active|inactive|approved|rejected|draft|published)["\']',
    re.IGNORECASE,
)

# Return-value patterns like `return Math.min(base, 200)`
RETURN_VALUE_PATTERN = re.compile(
    r'return\s+.*?(\d{2,}(?:\.\d+)?)',
    re.IGNORECASE,
)

# Multiplier / percentage patterns like `* 0.1` or `* 0.05`
MULTIPLIER_PATTERN = re.compile(
    r'\*\s*(0\.\d+)',
)


class IntentDetector:
    """
    Scans code for decisions that need intent captured.

    Usage:
        detector = IntentDetector()
        flags = detector.scan_file('src/discount.js', code_content, ai_confidence=0.8)
    """

    # ── AI-confidence scoring ─────────────────────────────────────────────
    @staticmethod
    def estimate_ai_confidence(commit_message='', pr_body='',
                               additions=0, time_between_commits_secs=None):
        """
        Return a float 0-1 estimating whether this code was AI-generated.

        Signals:
          - Commit message keywords  → +0.35
          - PR body keywords         → +0.25
          - Commit speed (>50 lines in <60s) → +0.25
          - Uniform style heuristic  → +0.15  (stubbed; always adds 0.05)
        """
        score = 0.0
        text = f"{commit_message} {pr_body}".lower()

        # Signal 1: keywords
        for kw in AI_KEYWORDS:
            if kw in text:
                score += 0.35
                break

        # Signal 2: PR body keywords (additional weight)
        if pr_body:
            pr_lower = pr_body.lower()
            for kw in AI_KEYWORDS:
                if kw in pr_lower:
                    score += 0.25
                    break

        # Signal 3: commit speed
        if time_between_commits_secs is not None and additions > 0:
            lines_per_sec = additions / max(time_between_commits_secs, 1)
            if lines_per_sec > 0.8:  # >50 lines per minute ≈ 0.83 lines/sec
                score += 0.25

        # Signal 4: uniform style heuristic (simple stub)
        score += 0.05

        return min(score, 1.0)

    # ── File scanning ─────────────────────────────────────────────────────
    def scan_file(self, file_path, content, ai_confidence=0.0):
        """
        Scan a single file and return a list of flag dicts.

        Each dict has:
          file_path, line_number, flag_type, detected_value,
          question, code_snippet, ai_confidence
        """
        if not content or not content.strip():
            return []

        flags = []
        lines = content.split('\n')

        for line_num, line in enumerate(lines, start=1):
            stripped = line.strip()

            # Skip comments and empty lines
            if not stripped or stripped.startswith('//') or stripped.startswith('#') \
               or stripped.startswith('*') or stripped.startswith('/*'):
                continue

            # ── Timeout / limit / delay ─────────────────────────────────
            for m in TIMEOUT_PATTERN.finditer(stripped):
                value = m.group(1)
                if value and int(value) not in (0, 1):
                    flags.append(self._make_flag(
                        file_path, line_num, 'timeout', value,
                        f"Why is this timeout/limit set to {value}?",
                        stripped, ai_confidence,
                    ))

            # ── Conditional thresholds ──────────────────────────────────
            for m in CONDITIONAL_THRESHOLD_PATTERN.finditer(stripped):
                value = m.group(1) or m.group(2)
                if value and self._is_meaningful_number(value):
                    flags.append(self._make_flag(
                        file_path, line_num, 'threshold', value,
                        f"Why is this threshold set to {value}?",
                        stripped, ai_confidence,
                    ))

            # ── Return-value magic numbers ──────────────────────────────
            for m in RETURN_VALUE_PATTERN.finditer(stripped):
                value = m.group(1)
                if value and self._is_meaningful_number(value):
                    flags.append(self._make_flag(
                        file_path, line_num, 'magic_number', value,
                        f"Why is the return value capped/set to {value}?",
                        stripped, ai_confidence,
                    ))

            # ── Multiplier / percentage values ──────────────────────────
            for m in MULTIPLIER_PATTERN.finditer(stripped):
                value = m.group(1)
                pct = round(float(value) * 100, 1)
                flags.append(self._make_flag(
                    file_path, line_num, 'magic_number', value,
                    f"Why is this multiplier set to {value} ({pct}%)?",
                    stripped, ai_confidence,
                ))

            # ── Algorithm choices ───────────────────────────────────────
            for m in ALGORITHM_PATTERNS.finditer(stripped):
                algo = m.group(0)
                # Look for round/cost values near the algorithm
                round_match = re.search(r'(\d+)', stripped[m.end():])
                if round_match:
                    rounds = round_match.group(1)
                    flags.append(self._make_flag(
                        file_path, line_num, 'algorithm_choice',
                        f"{algo}({rounds})",
                        f"Why was {algo} chosen with {rounds} rounds/iterations?",
                        stripped, ai_confidence,
                    ))
                else:
                    flags.append(self._make_flag(
                        file_path, line_num, 'algorithm_choice', algo,
                        f"Why was {algo} chosen over alternatives?",
                        stripped, ai_confidence,
                    ))

            # ── String assumptions ──────────────────────────────────────
            for m in STRING_ASSUMPTION_PATTERN.finditer(stripped):
                value = m.group(0).strip("'\"")
                flags.append(self._make_flag(
                    file_path, line_num, 'string_assumption', value,
                    f"Why is '{value}' hard-coded here? Is this an assumption?",
                    stripped, ai_confidence,
                ))

            # ── General magic numbers (fallback) ────────────────────────
            for m in MAGIC_NUMBER_PATTERN.finditer(stripped):
                value = m.group(1)
                if value and self._is_meaningful_number(value):
                    # Avoid duplicates from earlier patterns
                    existing_values = {f['detected_value'] for f in flags if f['line_number'] == line_num}
                    if value not in existing_values:
                        flags.append(self._make_flag(
                            file_path, line_num, 'magic_number', value,
                            f"Why is this value set to {value}?",
                            stripped, ai_confidence,
                        ))

        # Deduplicate flags on same line with same value
        seen = set()
        unique_flags = []
        for f in flags:
            key = (f['line_number'], f['detected_value'], f['flag_type'])
            if key not in seen:
                seen.add(key)
                unique_flags.append(f)

        return unique_flags

    # ── Helpers ────────────────────────────────────────────────────────────
    @staticmethod
    def _is_meaningful_number(value_str):
        """Return True if the number is 'interesting' (not 0, 1, 2, 10, 100)."""
        try:
            num = float(value_str)
            trivial = {0, 1, 2, 10, 100, 1000, -1}
            return num not in trivial and num > 1
        except ValueError:
            return False

    @staticmethod
    def _make_flag(file_path, line_number, flag_type, detected_value,
                   question, code_snippet, ai_confidence):
        return {
            'file_path': file_path,
            'line_number': line_number,
            'flag_type': flag_type,
            'detected_value': str(detected_value),
            'question': question,
            'code_snippet': code_snippet,
            'ai_confidence': ai_confidence,
        }

    def scan_pr_files(self, files_with_content, commit_message='',
                      pr_body='', additions=0):
        """
        Convenience method: scan multiple files from a PR.

        files_with_content: list of {'path': str, 'content': str}
        Returns: list of flag dicts (all files combined).
        """
        ai_conf = self.estimate_ai_confidence(
            commit_message=commit_message,
            pr_body=pr_body,
            additions=additions,
        )

        all_flags = []
        for f in files_with_content:
            file_flags = self.scan_file(f['path'], f['content'], ai_confidence=ai_conf)
            all_flags.extend(file_flags)

        return all_flags
