# Generated by Django 4.2.28 on 2026-02-27 16:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_pranalysis_documentationgeneration_commitanalysis_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_configured",
                    models.BooleanField(
                        default=False, help_text="Webhook successfully set up on GitHub"
                    ),
                ),
                (
                    "github_webhook_id",
                    models.CharField(
                        blank=True,
                        help_text="GitHub's webhook ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("webhook_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "webhook_secret",
                    models.CharField(
                        blank=True,
                        help_text="Secret for webhook signature verification",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "events",
                    models.JSONField(
                        default=list,
                        help_text="List of GitHub events this webhook listens to",
                    ),
                ),
                (
                    "last_ping",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last successful ping from GitHub",
                        null=True,
                    ),
                ),
                (
                    "last_delivery",
                    models.DateTimeField(
                        blank=True, help_text="Last event delivery", null=True
                    ),
                ),
                (
                    "consecutive_failures",
                    models.IntegerField(
                        default=0, help_text="Count of consecutive failed deliveries"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Webhook is active and receiving events"
                    ),
                ),
                ("last_error", models.TextField(blank=True, null=True)),
                ("error_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "repository",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_config",
                        to="core.repository",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Configuration",
                "verbose_name_plural": "Webhook Configurations",
                "db_table": "webhook_configurations",
            },
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auto_analyze_prs",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically analyze PRs when opened/updated",
                    ),
                ),
                (
                    "skip_draft_prs",
                    models.BooleanField(
                        default=True, help_text="Skip analysis for draft PRs"
                    ),
                ),
                (
                    "min_lines_for_analysis",
                    models.IntegerField(
                        default=50,
                        help_text="Minimum changed lines to trigger analysis",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "auto_post_comments",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically post analysis to GitHub (vs manual review)",
                    ),
                ),
                (
                    "auto_update_docs",
                    models.BooleanField(
                        default=False, help_text="Automatically update documentation"
                    ),
                ),
                (
                    "docs_update_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("manual", "Manual Only"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                (
                    "docs_min_changes",
                    models.IntegerField(
                        default=100,
                        help_text="Minimum code changes to trigger doc update",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "auto_generate_insights",
                    models.BooleanField(
                        default=True, help_text="Automatically generate insights"
                    ),
                ),
                (
                    "insights_frequency",
                    models.CharField(
                        choices=[
                            ("realtime", "Real-time"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("manual", "Manual Only"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                (
                    "email_critical_issues",
                    models.BooleanField(
                        default=True,
                        help_text="Email alerts for critical security issues",
                    ),
                ),
                (
                    "email_daily_digest",
                    models.BooleanField(default=False, help_text="Daily summary email"),
                ),
                (
                    "slack_notifications",
                    models.BooleanField(
                        default=False, help_text="Send notifications to Slack"
                    ),
                ),
                (
                    "slack_webhook_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "daily_token_limit",
                    models.IntegerField(
                        default=100000,
                        help_text="Daily API token limit",
                        validators=[django.core.validators.MinValueValidator(1000)],
                    ),
                ),
                (
                    "pause_on_limit",
                    models.BooleanField(
                        default=True, help_text="Pause automation when limit reached"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preference",
                "verbose_name_plural": "User Preferences",
                "db_table": "user_preferences",
            },
        ),
        migrations.CreateModel(
            name="ReviewerRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github_username", models.CharField(max_length=200)),
                (
                    "reviewer_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("shadow", "Shadow"),
                        ],
                        default="secondary",
                        max_length=20,
                    ),
                ),
                ("confidence_score", models.IntegerField(default=0)),
                ("recommendation_reason", models.TextField(blank=True)),
                ("files_relevant", models.JSONField(blank=True, default=list)),
                ("expertise_areas", models.JSONField(blank=True, default=list)),
                ("requested_on_github", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pull_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewer_recommendations",
                        to="core.pullrequest",
                    ),
                ),
            ],
            options={
                "db_table": "reviewer_recommendations",
            },
        ),
        migrations.CreateModel(
            name="RepositorySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "override_global",
                    models.BooleanField(
                        default=False,
                        help_text="Use custom settings instead of global preferences",
                    ),
                ),
                ("auto_analyze_prs", models.BooleanField(blank=True, null=True)),
                ("skip_draft_prs", models.BooleanField(blank=True, null=True)),
                (
                    "min_lines_for_analysis",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("auto_post_comments", models.BooleanField(blank=True, null=True)),
                ("auto_update_docs", models.BooleanField(blank=True, null=True)),
                (
                    "docs_update_frequency",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "docs_min_changes",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("auto_generate_insights", models.BooleanField(blank=True, null=True)),
                (
                    "insights_frequency",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "enable_pr_analysis",
                    models.BooleanField(
                        default=True, help_text="Enable PR analysis for this repo"
                    ),
                ),
                (
                    "enable_insights",
                    models.BooleanField(
                        default=True, help_text="Enable insights generation"
                    ),
                ),
                (
                    "enable_documentation",
                    models.BooleanField(
                        default=True, help_text="Enable documentation updates"
                    ),
                ),
                (
                    "enable_webhooks",
                    models.BooleanField(
                        default=True, help_text="Enable webhook automation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "repository",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="core.repository",
                    ),
                ),
            ],
            options={
                "verbose_name": "Repository Setting",
                "verbose_name_plural": "Repository Settings",
                "db_table": "repository_settings",
            },
        ),
        migrations.CreateModel(
            name="PRDescriptionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generated_description", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("features", models.JSONField(blank=True, default=list)),
                ("bug_fixes", models.JSONField(blank=True, default=list)),
                ("breaking_changes", models.JSONField(blank=True, default=list)),
                ("refactors", models.JSONField(blank=True, default=list)),
                ("has_tests", models.BooleanField(default=False)),
                ("requires_migration", models.BooleanField(default=False)),
                ("applied_to_github", models.BooleanField(default=False)),
                ("tokens_used", models.IntegerField(default=0)),
                ("generation_time", models.FloatField(default=0.0)),
                ("model_used", models.CharField(blank=True, max_length=100)),
                ("user_approved", models.BooleanField(default=False)),
                ("user_edited", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pull_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="description_template",
                        to="core.pullrequest",
                    ),
                ),
            ],
            options={
                "db_table": "pr_description_templates",
            },
        ),
        migrations.CreateModel(
            name="DeveloperExpertise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github_username", models.CharField(max_length=200)),
                ("expertise_areas", models.JSONField(blank=True, default=list)),
                ("expertise_map", models.JSONField(blank=True, default=dict)),
                ("total_commits", models.IntegerField(default=0)),
                ("total_prs_authored", models.IntegerField(default=0)),
                ("files_touched", models.JSONField(blank=True, default=list)),
                ("active_days", models.IntegerField(default=0)),
                ("first_contribution", models.DateTimeField(blank=True, null=True)),
                ("last_contribution", models.DateTimeField(blank=True, null=True)),
                ("analyzed_at", models.DateTimeField(auto_now=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developer_expertise",
                        to="core.repository",
                    ),
                ),
            ],
            options={
                "db_table": "developer_expertise",
                "unique_together": {("repository", "github_username")},
            },
        ),
        migrations.CreateModel(
            name="CostTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Date of usage")),
                ("pr_analyses_count", models.IntegerField(default=0)),
                ("insights_generated_count", models.IntegerField(default=0)),
                ("docs_updated_count", models.IntegerField(default=0)),
                (
                    "tokens_used",
                    models.IntegerField(default=0, help_text="Total tokens consumed"),
                ),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                (
                    "api_calls",
                    models.IntegerField(
                        default=0, help_text="Number of API requests made"
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_tracking",
                        to="core.repository",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_tracking",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cost_tracking",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["user", "-date"], name="cost_tracki_user_id_e85f26_idx"
                    ),
                    models.Index(
                        fields=["repository", "-date"],
                        name="cost_tracki_reposit_745d4e_idx",
                    ),
                ],
                "unique_together": {("user", "repository", "date")},
            },
        ),
        migrations.CreateModel(
            name="CodeOwnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("primary_owner", models.CharField(max_length=200)),
                ("contributors", models.JSONField(blank=True, default=list)),
                ("commits_count", models.IntegerField(default=0)),
                ("lines_authored", models.IntegerField(default=0)),
                ("expertise_score", models.IntegerField(default=0)),
                ("last_modified", models.DateTimeField(blank=True, null=True)),
                ("analyzed_at", models.DateTimeField(auto_now=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_ownerships",
                        to="core.repository",
                    ),
                ),
            ],
            options={
                "db_table": "code_ownership",
                "unique_together": {("repository", "file_path")},
            },
        ),
        migrations.CreateModel(
            name="AutomationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("pr_analysis", "PR Analysis"),
                            ("insight_generation", "Insight Generation"),
                            ("doc_update", "Documentation Update"),
                            ("webhook_event", "Webhook Event"),
                            ("scheduled_task", "Scheduled Task"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        help_text="What triggered this action (webhook, schedule, manual)",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable description of the action"
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        help_text="Celery task ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "result_summary",
                    models.TextField(
                        blank=True,
                        help_text="Summary of what was accomplished",
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("tokens_used", models.IntegerField(default=0)),
                ("api_calls_made", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pull_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.pullrequest",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_logs",
                        to="core.repository",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "automation_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="automation__created_5e53f1_idx"
                    ),
                    models.Index(
                        fields=["status"], name="automation__status_bce883_idx"
                    ),
                    models.Index(
                        fields=["action_type"], name="automation__action__ead641_idx"
                    ),
                ],
            },
        ),
    ]
