# Generated by Django 4.2.28 on 2026-06-14 16:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_webhookconfiguration_userpreferences_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('symbol_type', models.CharField(choices=[('function', 'Function'), ('class', 'Class'), ('variable', 'Variable'), ('import', 'Import')], max_length=20)),
                ('symbol_name', models.CharField(max_length=255)),
                ('line_start', models.IntegerField(default=0)),
                ('line_end', models.IntegerField(default=0)),
                ('signature', models.JSONField(blank=True, default=dict)),
                ('dependencies', models.JSONField(blank=True, default=list)),
                ('dependents', models.JSONField(blank=True, default=list)),
                ('hash', models.CharField(blank=True, max_length=64)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('pull_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symbol_maps', to='core.pullrequest')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol_maps', to='core.repository')),
            ],
            options={
                'db_table': 'symbol_maps',
                'indexes': [models.Index(fields=['repository', 'file_path'], name='symbol_maps_reposit_a72b23_idx'), models.Index(fields=['symbol_name'], name='symbol_maps_symbol__d7d01d_idx'), models.Index(fields=['pull_request'], name='symbol_maps_pull_re_139ff8_idx'), models.Index(fields=['repository', 'symbol_name'], name='symbol_maps_reposit_46aee5_idx')],
            },
        ),
        migrations.CreateModel(
            name='DependencyUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255)),
                ('from_version', models.CharField(max_length=50)),
                ('to_version', models.CharField(max_length=50)),
                ('update_type', models.CharField(choices=[('major', 'Major'), ('minor', 'Minor'), ('patch', 'Patch')], max_length=10)),
                ('applied', models.BooleanField(default=False)),
                ('migration_script_used', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('pull_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependency_updates', to='core.pullrequest')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_updates', to='core.repository')),
            ],
            options={
                'db_table': 'dependency_updates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['repository', 'package_name'], name='dependency__reposit_cb1a79_idx')],
            },
        ),
        migrations.CreateModel(
            name='DependencyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255)),
                ('current_version', models.CharField(max_length=50)),
                ('latest_version', models.CharField(blank=True, max_length=50)),
                ('latest_safe_version', models.CharField(blank=True, max_length=50)),
                ('has_breaking_changes', models.BooleanField(default=False)),
                ('breaking_changes', models.JSONField(blank=True, default=list)),
                ('changelog_url', models.URLField(blank=True, max_length=500)),
                ('impact_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('files_affected', models.JSONField(blank=True, default=list)),
                ('code_patterns_affected', models.JSONField(blank=True, default=list)),
                ('estimated_refactor_hours', models.IntegerField(default=0)),
                ('migration_script', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_analyses', to='core.repository')),
            ],
            options={
                'db_table': 'dependency_analyses',
                'ordering': ['-impact_score'],
                'indexes': [models.Index(fields=['repository', 'package_name'], name='dependency__reposit_8832a2_idx'), models.Index(fields=['impact_score'], name='dependency__impact__71154c_idx'), models.Index(fields=['-analyzed_at'], name='dependency__analyze_2bd6fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConflictDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('file_level', 'File Level'), ('function_level', 'Function Level'), ('symbol_level', 'Symbol Level'), ('semantic', 'Semantic'), ('dependency', 'Dependency')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('affected_files', models.JSONField(blank=True, default=list)),
                ('conflicting_symbols', models.JSONField(blank=True, default=list)),
                ('resolution_suggestion', models.TextField(blank=True)),
                ('merge_order', models.JSONField(blank=True, default=list)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notified', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('pr_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_pr1', to='core.pullrequest')),
                ('pr_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_pr2', to='core.pullrequest')),
            ],
            options={
                'db_table': 'conflict_detections',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['pr_1', 'pr_2'], name='conflict_de_pr_1_id_d2862c_idx'), models.Index(fields=['severity'], name='conflict_de_severit_ebf93a_idx'), models.Index(fields=['is_resolved'], name='conflict_de_is_reso_5a3481_idx'), models.Index(fields=['-detected_at'], name='conflict_de_detecte_d1223f_idx')],
            },
        ),
    ]
