# Generated by Django 4.2.28 on 2026-06-15 16:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_symbolmap_dependencyupdate_dependencyanalysis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileComprehensionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('ai_authorship_pct', models.FloatField(default=0.0, help_text='Estimated percentage of code written by AI (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('human_edit_count', models.IntegerField(default=0, help_text='Number of meaningful human edits after initial commit')),
                ('total_commit_count', models.IntegerField(default=0, help_text='Total commits touching this file')),
                ('unique_contributors', models.IntegerField(default=0, help_text='Number of unique developers who meaningfully touched this file')),
                ('comprehension_score', models.IntegerField(default=0, help_text='Final comprehension score (0=nobody understands, 100=well understood)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('risk_level', models.CharField(choices=[('green', 'Well Understood'), ('amber', 'Partial Understanding'), ('red', 'Nobody Understands')], default='green', max_length=10)),
                ('last_human_edit_at', models.DateTimeField(blank=True, help_text='When the last human (non-AI) edit occurred', null=True)),
                ('suggested_reviewer', models.CharField(blank=True, help_text='Best person to review/document this file', max_length=200)),
                ('last_analyzed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprehension_scores', to='core.repository')),
            ],
            options={
                'db_table': 'file_comprehension_scores',
                'ordering': ['comprehension_score'],
                'indexes': [models.Index(fields=['repository', 'risk_level'], name='file_compre_reposit_a6e388_idx'), models.Index(fields=['comprehension_score'], name='file_compre_compreh_a2f08c_idx'), models.Index(fields=['-last_analyzed_at'], name='file_compre_last_an_2819e1_idx')],
                'unique_together': {('repository', 'file_path')},
            },
        ),
    ]
